package com.xxl.wechat.model.generator;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {
	
	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("BOOK_ROOM_TASK", "ID", BookRoomTask.class);
		arp.addMapping("FIX_ASSET_TASK", "ID", FixAssetTask.class);
		arp.addMapping("SY_ATTACHMENT", "ID", SyAttachment.class);
		arp.addMapping("SY_MAIN_CATEGORY", "ID", SyMainCategory.class);
		arp.addMapping("SY_ROOM", "ID", SyRoom.class);
		arp.addMapping("SY_SUB_CATEGORY", "ID", SySubCategory.class);
		arp.addMapping("SY_USER", "ID", SyUser.class);
	}
}

