package com.xxl.wechat.model.generator;

import com.xxl.wechat.model.generator.base.BaseBookRoomTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class BookRoomTask extends BaseBookRoomTask<BookRoomTask> {
	
}
