package com.xxl.wechat.model.generator;

import com.xxl.wechat.model.generator.base.BaseFixAssetTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class FixAssetTask extends BaseFixAssetTask<FixAssetTask> {
	
}
