package com.xxl.wechat.model.generator;

import com.xxl.wechat.model.generator.base.BaseSyAttachment;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SyAttachment extends BaseSyAttachment<SyAttachment> {
	
}
