package com.xxl.wechat.model.generator;

import com.xxl.wechat.model.generator.base.BaseSyMainCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SyMainCategory extends BaseSyMainCategory<SyMainCategory> {
	
}
