package com.xxl.wechat.model.generator;

import com.xxl.wechat.model.generator.base.BaseSyRoom;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SyRoom extends BaseSyRoom<SyRoom> {
	
}
