package com.xxl.wechat.model.generator;

import com.xxl.wechat.model.generator.base.BaseSySubCategory;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SySubCategory extends BaseSySubCategory<SySubCategory> {
	
}
