package com.xxl.wechat.model.generator;

import com.xxl.wechat.model.generator.base.BaseSyUser;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class SyUser extends BaseSyUser<SyUser> {
	
}
