package com.xxl.wechat.model.generator;

import com.xxl.wechat.model.generator.base.BaseWechatNoticeTask;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WechatNoticeTask extends BaseWechatNoticeTask<WechatNoticeTask> {
	
}
