package com.xxl.wechat.model.generator.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSyAttachment<M extends BaseSyAttachment<M>> extends Model<M> implements IBean {

	public void setId(java.lang.String id) {
		set("ID", id);
	}
	
	public java.lang.String getId() {
		return getStr("ID");
	}

	public void setBusinessId(java.lang.Integer businessId) {
		set("BUSINESS_ID", businessId);
	}
	
	public java.lang.Integer getBusinessId() {
		return getInt("BUSINESS_ID");
	}

	public void setName(java.lang.String name) {
		set("NAME", name);
	}
	
	public java.lang.String getName() {
		return getStr("NAME");
	}

	public void setType(java.lang.Integer type) {
		set("TYPE", type);
	}
	
	public java.lang.Integer getType() {
		return getInt("TYPE");
	}

	public void setFromModule(java.lang.Integer fromModule) {
		set("FROM_MODULE", fromModule);
	}
	
	public java.lang.Integer getFromModule() {
		return getInt("FROM_MODULE");
	}

	public void setUrl(java.lang.String url) {
		set("URL", url);
	}
	
	public java.lang.String getUrl() {
		return getStr("URL");
	}

	public void setSuffix(java.lang.String suffix) {
		set("SUFFIX", suffix);
	}
	
	public java.lang.String getSuffix() {
		return getStr("SUFFIX");
	}

	public void setSize(java.lang.Long size) {
		set("SIZE", size);
	}
	
	public java.lang.Long getSize() {
		return getLong("SIZE");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("CREATE_DATE", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("CREATE_DATE");
	}

	public void setCreateUserId(java.lang.Integer createUserId) {
		set("CREATE_USER_ID", createUserId);
	}
	
	public java.lang.Integer getCreateUserId() {
		return getInt("CREATE_USER_ID");
	}

	public void setStatus(java.lang.Integer status) {
		set("STATUS", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("STATUS");
	}

}
