package com.xxl.wechat.model.generator.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseBookRoomTask<M extends BaseBookRoomTask<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("ID", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("ID");
	}

	public void setRoomId(java.lang.Integer roomId) {
		set("ROOM_ID", roomId);
	}
	
	public java.lang.Integer getRoomId() {
		return getInt("ROOM_ID");
	}

	public void setBookDate(java.lang.String bookDate) {
		set("BOOK_DATE", bookDate);
	}
	
	public java.lang.String getBookDate() {
		return getStr("BOOK_DATE");
	}

	public void setBookUserId(java.lang.Integer bookUserId) {
		set("BOOK_USER_ID", bookUserId);
	}
	
	public java.lang.Integer getBookUserId() {
		return getInt("BOOK_USER_ID");
	}

	public void setBookStartTime(java.util.Date bookStartTime) {
		set("BOOK_START_TIME", bookStartTime);
	}
	
	public java.util.Date getBookStartTime() {
		return get("BOOK_START_TIME");
	}

	public void setBookEndTime(java.util.Date bookEndTime) {
		set("BOOK_END_TIME", bookEndTime);
	}
	
	public java.util.Date getBookEndTime() {
		return get("BOOK_END_TIME");
	}

	public void setDepart(java.lang.String depart) {
		set("DEPART", depart);
	}
	
	public java.lang.String getDepart() {
		return getStr("DEPART");
	}

	public void setUseReason(java.lang.String useReason) {
		set("USE_REASON", useReason);
	}
	
	public java.lang.String getUseReason() {
		return getStr("USE_REASON");
	}

	public void setDevice(java.lang.String device) {
		set("DEVICE", device);
	}
	
	public java.lang.String getDevice() {
		return getStr("DEVICE");
	}

	public void setRemark(java.lang.String remark) {
		set("REMARK", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("REMARK");
	}

	public void setNeedCamera(java.lang.Integer needCamera) {
		set("NEED_CAMERA", needCamera);
	}
	
	public java.lang.Integer getNeedCamera() {
		return getInt("NEED_CAMERA");
	}

	public void setSpecialRequire(java.lang.Integer specialRequire) {
		set("SPECIAL_REQUIRE", specialRequire);
	}
	
	public java.lang.Integer getSpecialRequire() {
		return getInt("SPECIAL_REQUIRE");
	}

	public void setStatus(java.lang.Integer status) {
		set("STATUS", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("STATUS");
	}

	public void setResponsibleUser(java.lang.String responsibleUser) {
		set("RESPONSIBLE_USER", responsibleUser);
	}
	
	public java.lang.String getResponsibleUser() {
		return getStr("RESPONSIBLE_USER");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("CREATE_DATE", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("CREATE_DATE");
	}

	public void setCreateUserId(java.lang.Integer createUserId) {
		set("CREATE_USER_ID", createUserId);
	}
	
	public java.lang.Integer getCreateUserId() {
		return getInt("CREATE_USER_ID");
	}

	public void setVersion(java.lang.Integer version) {
		set("VERSION", version);
	}
	
	public java.lang.Integer getVersion() {
		return getInt("VERSION");
	}

}
