package com.xxl.wechat.model.generator.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseWechatNoticeTask<M extends BaseWechatNoticeTask<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("ID", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("ID");
	}

	public void setUserId(java.lang.String userId) {
		set("USER_ID", userId);
	}
	
	public java.lang.String getUserId() {
		return getStr("USER_ID");
	}

	public void setSendMsg(java.lang.String sendMsg) {
		set("SEND_MSG", sendMsg);
	}
	
	public java.lang.String getSendMsg() {
		return getStr("SEND_MSG");
	}

	public void setRemark(java.lang.String remark) {
		set("REMARK", remark);
	}
	
	public java.lang.String getRemark() {
		return getStr("REMARK");
	}

	public void setResult(java.lang.String result) {
		set("RESULT", result);
	}
	
	public java.lang.String getResult() {
		return getStr("RESULT");
	}

	public void setStatus(java.lang.Integer status) {
		set("STATUS", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("STATUS");
	}

	public void setErrorCode(java.lang.Integer errorCode) {
		set("ERROR_CODE", errorCode);
	}
	
	public java.lang.Integer getErrorCode() {
		return getInt("ERROR_CODE");
	}

	public void setErrMsg(java.lang.String errMsg) {
		set("ERR_MSG", errMsg);
	}
	
	public java.lang.String getErrMsg() {
		return getStr("ERR_MSG");
	}

	public void setInvalidUser(java.lang.String invalidUser) {
		set("INVALID_USER", invalidUser);
	}
	
	public java.lang.String getInvalidUser() {
		return getStr("INVALID_USER");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("CREATE_DATE", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("CREATE_DATE");
	}

}
