package com.xxl.wechat.model.generator.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSyUser<M extends BaseSyUser<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("ID", id);
	}
	
	public java.lang.Integer getId() {
		return getInt("ID");
	}

	public void setWechatUserId(java.lang.String wechatUserId) {
		set("WECHAT_USER_ID", wechatUserId);
	}
	
	public java.lang.String getWechatUserId() {
		return getStr("WECHAT_USER_ID");
	}

	public void setClassId(java.lang.Integer classId) {
		set("CLASS_ID", classId);
	}
	
	public java.lang.Integer getClassId() {
		return getInt("CLASS_ID");
	}

	public void setSchoolId(java.lang.Integer schoolId) {
		set("SCHOOL_ID", schoolId);
	}
	
	public java.lang.Integer getSchoolId() {
		return getInt("SCHOOL_ID");
	}

	public void setUserName(java.lang.String userName) {
		set("USER_NAME", userName);
	}
	
	public java.lang.String getUserName() {
		return getStr("USER_NAME");
	}

	public void setRealName(java.lang.String realName) {
		set("REAL_NAME", realName);
	}
	
	public java.lang.String getRealName() {
		return getStr("REAL_NAME");
	}

	public void setSex(java.lang.Integer sex) {
		set("SEX", sex);
	}
	
	public java.lang.Integer getSex() {
		return getInt("SEX");
	}

	public void setPassword(java.lang.String password) {
		set("PASSWORD", password);
	}
	
	public java.lang.String getPassword() {
		return getStr("PASSWORD");
	}

	public void setStatus(java.lang.Integer status) {
		set("STATUS", status);
	}
	
	public java.lang.Integer getStatus() {
		return getInt("STATUS");
	}

	public void setOpenId(java.lang.String openId) {
		set("OPEN_ID", openId);
	}
	
	public java.lang.String getOpenId() {
		return getStr("OPEN_ID");
	}

	public void setPhone(java.lang.String phone) {
		set("PHONE", phone);
	}
	
	public java.lang.String getPhone() {
		return getStr("PHONE");
	}

	public void setGender(java.lang.Integer gender) {
		set("GENDER", gender);
	}
	
	public java.lang.Integer getGender() {
		return getInt("GENDER");
	}

	public void setAvatar(java.lang.String avatar) {
		set("AVATAR", avatar);
	}
	
	public java.lang.String getAvatar() {
		return getStr("AVATAR");
	}

	public void setPosition(java.lang.String position) {
		set("POSITION", position);
	}
	
	public java.lang.String getPosition() {
		return getStr("POSITION");
	}

	public void setQq(java.lang.String qq) {
		set("QQ", qq);
	}
	
	public java.lang.String getQq() {
		return getStr("QQ");
	}

	public void setEmail(java.lang.String email) {
		set("EMAIL", email);
	}
	
	public java.lang.String getEmail() {
		return getStr("EMAIL");
	}

	public void setWechatCode(java.lang.String wechatCode) {
		set("WECHAT_CODE", wechatCode);
	}
	
	public java.lang.String getWechatCode() {
		return getStr("WECHAT_CODE");
	}

	public void setUserType(java.lang.Integer userType) {
		set("USER_TYPE", userType);
	}
	
	public java.lang.Integer getUserType() {
		return getInt("USER_TYPE");
	}

	public void setCreateDate(java.util.Date createDate) {
		set("CREATE_DATE", createDate);
	}
	
	public java.util.Date getCreateDate() {
		return get("CREATE_DATE");
	}

	public void setCreateUserId(java.lang.String createUserId) {
		set("CREATE_USER_ID", createUserId);
	}
	
	public java.lang.String getCreateUserId() {
		return getStr("CREATE_USER_ID");
	}

	public void setVersion(java.lang.String version) {
		set("VERSION", version);
	}
	
	public java.lang.String getVersion() {
		return getStr("VERSION");
	}

}
