CREATE DATABASE wechat DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
create user 'wechat'@'%' identified by '1234+asdf';
grant all privileges on wechat.* to 'wechat'@'%';

/**用户*/
DROP TABLE IF EXISTS `SY_USER`;
 CREATE TABLE `SY_USER` (
  `ID` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `WECHAT_USER_ID` varchar(255) NOT NULL COMMENT '微信认证后的USER_ID',
  `CLASS_ID` int(11) DEFAULT NULL COMMENT '班级ID',
  `SCHOOL_ID` int(11) DEFAULT NULL COMMENT '学校ID',
  `USER_NAME` varchar(256) DEFAULT NULL COMMENT '用户名',
  `REAL_NAME` varchar(256) DEFAULT NULL COMMENT '真实姓名',
  `SEX` tinyint(4) DEFAULT NULL COMMENT '姓别',
  `PASSWORD` varchar(256) DEFAULT NULL COMMENT '密码',
  `STATUS` tinyint(4) NOT NULL COMMENT '状态',
  `OPEN_ID` varchar(256)  DEFAULT NULL COMMENT '该公众号下的用户惟一标识',
  `PHONE` varchar(11) DEFAULT NULL COMMENT '手机号',
  `GENDER` int(11) DEFAULT NULL COMMENT '我也不知道是啥',
  `AVATAR` varchar(256) DEFAULT NULL COMMENT '用户头像URL地址',
  `POSITION` varchar(256) DEFAULT NULL COMMENT '职位',
  `QQ` varchar(256) DEFAULT NULL COMMENT 'QQ号',
  `EMAIL` varchar(256) DEFAULT NULL COMMENT '邮箱',
  `WECHAT_CODE` varchar(256) DEFAULT NULL COMMENT '微信号',
  `USER_TYPE` tinyint(4) DEFAULT NULL COMMENT '用户类型 1.管理员  2.老师 3.后勤维修 4.信息中心维修 5.领导',
  `CREATE_DATE` datetime NOT NULL COMMENT '创建日期',
  `CREATE_USER_ID` varchar(255)  NOT NULL COMMENT '创建人',
   `VERSION` varchar(256) DEFAULT NULL COMMENT '版本号',
   UNIQUE KEY `AK_UNI_USER_NAME` (`WECHAT_USER_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='用户表';

DROP TABLE IF EXISTS `FIX_ASSET_TASK`;
CREATE TABLE `FIX_ASSET_TASK` (
  `ID` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `FIX_USER_ID` int(11) DEFAULT NULL COMMENT '负责修理用户ID',
  `APPLY_USER_ID` int(11)  NOT NULL COMMENT '发起申请用户ID',
  `ASSET_TYPE` varchar(256) DEFAULT NULL COMMENT '物品大类(单选)',
  `ASSET_SUB_TYPE` varchar(256) DEFAULT NULL COMMENT '物品小类(多选，多个用逗号分隔)',
  `ASSET_NAME` varchar(256) DEFAULT NULL COMMENT '物品名称',
  `ASSET_LOCATION` varchar(256) DEFAULT NULL COMMENT '物品位置',
  `BELONG_CAMPUS` varchar(1) default  null  COMMENT '所属校区',
  `FIX_REASON` varchar(2048) DEFAULT NULL COMMENT '维修原因',
  `STATUS` tinyint(4) NOT NULL COMMENT '1.其它 2.已上报领导 3.已联系厂商 4.维修需要很久，慢慢等待  5.没有问题了  6 修理完成',
  `APPLY_DATE` datetime DEFAULT NULL COMMENT '申请时间',
  `START_FIX_DATE` datetime DEFAULT NULL COMMENT '接单时间',
  `FIXED_DATE` datetime DEFAULT NULL COMMENT '处理完毕时间',
  `VERSION` int NOT NULL COMMENT '版本号（用于乐观锁）'
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8 COMMENT='资产维修任务表';


CREATE TABLE `SY_ATTACHMENT` (
  `ID` varchar(128) NOT NULL,
  `BUSINESS_ID` int(11) DEFAULT NULL COMMENT '业务ID',
  `NAME` varchar(512) DEFAULT NULL COMMENT '文件名',
  `TYPE` int(11) NOT NULL COMMENT '文件类型',
  `FROM_MODULE` int(11) DEFAULT NULL COMMENT '来自哪个模块',
  `URL` varchar(256) NOT NULL COMMENT '文件路径',
  `SUFFIX` varchar(128) DEFAULT NULL COMMENT '文件后缀',
  `SIZE` bigint(20) DEFAULT NULL COMMENT '文件大小',
  `CREATE_DATE` datetime NOT NULL COMMENT '创建日期',
  `CREATE_USER_ID` int(11)  NOT NULL COMMENT '创建人',
  `STATUS` int(11) NOT NULL COMMENT '状态',
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='附件表';

DROP TABLE IF EXISTS `BOOK_ROOM_TASK`;
CREATE TABLE `BOOK_ROOM_TASK` (
  `ID` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `ROOM_ID` int(11) NOT NULL COMMENT '房间ID',
  `BOOK_DATE` varchar(128) DEFAULT NULL COMMENT '预订日期',
  `BOOK_USER_ID` int(11)  DEFAULT NULL COMMENT '预订人',
  `BOOK_START_TIME` datetime NOT NULL COMMENT '预订开始时间',
  `BOOK_END_TIME` datetime DEFAULT NULL COMMENT '预订结束时间',
  `DEPART` varchar(256) DEFAULT NULL COMMENT '使用部门',
  `USE_REASON` varchar(256) DEFAULT NULL COMMENT '使用事由',
  `DEVICE` varchar(256) DEFAULT NULL COMMENT '使用设备名称',
  `REMARK` varchar(256) DEFAULT NULL COMMENT '备注',
  `NEED_PHOTO` int DEFAULT NULL COMMENT '是否需要照相',
  `NEED_CAMERA` int DEFAULT NULL COMMENT '是否需要摄像',
  `SPECIAL_REQUIRE` varchar(512) DEFAULT NULL COMMENT '特殊要求',
  `STATUS` int DEFAULT  NULL COMMENT '状态',
  `RESPONSIBLE_USER` varchar(256) DEFAULT NULL COMMENT '责任人',
  `CREATE_DATE` datetime NOT NULL comment  '创建时间',
  `CREATE_USER_ID` int(11)  DEFAULT NULL COMMENT '创建人',
  `VERSION` int NOT NULL COMMENT '版本号（用于乐观锁）'
) ENGINE=InnoDB AUTO_INCREMENT=10000 DEFAULT CHARSET=utf8 COMMENT='预订房间表';


DROP TABLE IF EXISTS `SY_ROOM`;
CREATE TABLE `SY_ROOM` (
  `ID` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `NAME` varchar(256) NOT NULL COMMENT '房间名称',
  `REMARK` varchar(256) DEFAULT NULL COMMENT '备注',
  `CREATE_DATE` datetime NOT NULL comment  '创建时间'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='会议室表';



DROP TABLE IF EXISTS `SY_MAIN_CATEGORY`;
CREATE TABLE `SY_MAIN_CATEGORY` (
  `ID` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `NAME` varchar(256) NOT NULL COMMENT '名称',
  `SHORT_NAME` varchar(256) DEFAULT NULL COMMENT '简称',
  `REMARK` varchar(256) DEFAULT NULL COMMENT '备注',
  `CREATE_DATE` datetime NOT NULL comment  '创建时间'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='系统主分类';

DROP TABLE IF EXISTS `SY_SUB_CATEGORY`;
CREATE TABLE `SY_SUB_CATEGORY` (
  `ID` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `NAME` varchar(256) NOT NULL COMMENT '名称',
  `SHORT_NAME` varchar(256) DEFAULT NULL COMMENT '简称',
  `MAIN_CATEGORY_ID` int(11) default  NULL comment '外键',
  `REMARK` varchar(256) DEFAULT NULL COMMENT '备注',
  `CREATE_DATE` datetime NOT NULL comment  '创建时间'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='系统子分类';


DROP TABLE IF EXISTS `WECHAT_NOTICE_TASK`;
CREATE TABLE `WECHAT_NOTICE_TASK` (
  `ID` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `USER_ID` varchar(256) NOT NULL COMMENT '微信企业号用户ID,多个用|线分开',
  `SEND_MSG` varchar(1024) default  NULL comment '推送的消息',
  `REMARK` varchar(256) DEFAULT NULL COMMENT '备注',
  `RESULT` varchar(1024) DEFAULT  NULL comment '',
  `STATUS` int NOT NULL comment '',
  `ERROR_CODE` int default  null COMMENT '微信接口返回',
  `ERR_MSG` varchar(256) default  null COMMENT '微信接口返回',
  `INVALID_USER` varchar(256) default  null COMMENT '微信接口返回',
  `CREATE_DATE` datetime NOT NULL comment  '创建时间'
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='微信推送';



insert into WECHAT_NOTICE_TASK(ID,USER_ID,SEND_MSG,STATUS,CREATE_DATE) values(1,'WangPeng','您07-28 15的报修发生变化',0,'2018-04-01 18:55:55');


insert into SY_MAIN_CATEGORY values(3,'后勤中心','HQZX','','2018-04-01 18:55:55');
insert into SY_MAIN_CATEGORY values(4,'信息中心','XXZX','','2018-04-01 18:55:55');

insert into SY_SUB_CATEGORY values(40010,'电脑','DN',4,'','2018-04-01 18:55:55');
insert into SY_SUB_CATEGORY values(40020,'打印机','DYJ',4,'','2018-04-01 18:55:55');
insert into SY_SUB_CATEGORY values(40030,'大屏','DP',4,'','2018-04-01 18:55:55');
insert into SY_SUB_CATEGORY values(40040,'音箱','YX',4,'','2018-04-01 18:55:55');
insert into SY_SUB_CATEGORY values(40050,'IP电话','IPDH',4,'','2018-04-01 18:55:55');

insert into SY_SUB_CATEGORY values(30010,'黑板','HB',3,'','2018-04-01 18:55:55');
insert into SY_SUB_CATEGORY values(30020,'学生桌','XSZ',3,'','2018-04-01 18:55:55');
insert into SY_SUB_CATEGORY values(30030,'学生椅','XSY',3,'','2018-04-01 18:55:55');

insert into SY_ROOM VALUES(1,'大会议室','','2018-04-01 18:55:55');
insert into SY_ROOM VALUES(2,'小会议室','','2018-04-01 18:55:55');
insert into SY_ROOM VALUES(3,'报告厅','','2018-04-01 18:55:55');
insert into SY_ROOM VALUES(4,'风雨操场','','2018-04-01 18:55:55');

INSERT INTO SY_USER(ID,REAL_NAME,STATUS,CREATE_USER_ID,CREATE_DATE) VALUE('10000','王大鹏',1,'10000','2018-04-01 18:55:55');